port: '8889'
mysql:
  host: '127.0.0.1'
  port: '3306'
  name: 'chatcraft'
  user: 'root'
  password: 'root@123321'
redis:
  host: '127.0.0.1'
  port: '6379'

rabbitmq:
  host: "127.0.0.1"
  port: "5672"
  user: "guest"
  password: "guest"
